config/routes.rb
Rails.application.routes.draw do
  get 'orders/new/:pop_id', to: "orders#new", as: "new_order"
  get 'orders/success', to: "orders#success", as: "order_success"
  get 'orders/cancel', to: "orders#cancel", as: "order_cancel"
  devise_for :users
  
  root 'home#index'
  delete "/pops/:id", to: "pops#destroy", as: "delete_pop"

  resources :pops
  resources :orders
  resources :home

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pop.rb
class Pop < ApplicationRecord
  belongs_to :user
  has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :pops
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user! 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @pop = Pop.find(params[:pop_id])

    Stripe.api_key = ENV['STRIPE_SK_TEST']
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      success_url: order_success_url,
      cancel_url: order_cancel_url,
      line_items: [
        {
          name: @pop.name,
          description: "sold by #{@pop.user.email}",
          amount: (@pop.price * 100.00).to_i,
          currency: 'aud',
          quantity: 1
        }
      ]
      
    )
  end

  def success
    render html: "<h4>Thanks for your order!</h4>".html_safe
  end

  def cancel
    render html: "<h4>The order was cancelled.</h4>".html_safe
  end
end

app/controllers/pops_controller.rb
class PopsController < ApplicationController
  before_action :set_pop, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]
  

  # GET /pops or /pops.json
  def index
    @pops = Pop.all
  end

  # GET /pops/1 or /pops/1.json
  def show
  end

  # GET /pops/new
  def new
    @pop = Pop.new
  end

  # GET /pops/1/edit
  def edit
  end

  # POST /pops or /pops.json
  def create
    @pop = Pop.new(pop_params)
    @pop.user_id = current_user.id
    respond_to do |format|
      if @pop.save
        format.html { redirect_to @pop, notice: "Pop was successfully created." }
        format.json { render :show, status: :created, location: @pop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pop.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /pops/1 or /pops/1.json
  def update
    respond_to do |format|
      if @pop.update(pop_params)
        format.html { redirect_to @pop, notice: "Pop was successfully updated." }
        format.json { render :show, status: :ok, location: @pop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pops/1 or /pops/1.json
  def destroy
    @pop.destroy
    respond_to do |format|
      format.html { redirect_to pops_url, notice: "Pop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pop
      @pop = Pop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pop_params
      params.require(:pop).permit(:name, :description, :price, :category, :user_id, :picture)
    end

    def check_user
      if current_user.id == @pop.user_id
        return
        else
        flash[:alert] = "You are not authorised!"
        redirect_to root_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pops_helper.rb
module PopsHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
    <div class="row">
        <div class="col-md-3">
            <img src="https://res.cloudinary.com/jellysage/image/upload/v1616217811/cj9wx78xe6b8xtet3gwvfb9u61bx.jpg" class="index-image" />
        </div>

        <div class="col-md-6">
            <h1 class="display-3">Pop! Exchange!</h1>
            <p class = "lead"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum enim sem, placerat vitae bibendum non, dictum eget lorem. Praesent efficitur, lacus et mollis ullamcorper, est sapien malesuada turpis, eget convallis metus lectus in nulla.</p>
            <p class="lead">
                <%=link_to "  Browse Listing  ", pops_path, class:"btn btn-primary btn-lg"%>
            </p>
            <p class="lead">
                <%=link_to "  Create Listings ", new_pop_path, class:"btn btn-secondary btn-lg"%>
            </p>
        </div>

        <div class="col-md-3">
            <img src="https://res.cloudinary.com/jellysage/image/upload/v1616217811/cj9wx78xe6b8xtet3gwvfb9u61bx.jpg" class="index-image" />
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PopExchange</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-sm">
    <%= render "partial/navbar" %>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  <div class="container-sm">
  </body>
</html>

app/views/orders/new.html.erb
<div class="jumbotron">
    <div class="row">
        <div class="col-md-8">
        <h1>Your Order</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <ul>
                <dd> <%=@pop.name %> </dd>
                <dd> <%=@pop.description %> </dd>
                <dd> <%= "sold by #{@pop.user.email}"%> </dd>
                <dd> <%=number_to_currency @pop.price %> </dd>
            </ul>
        </div>
    </div>
</div>
<link type="button" class="btn btn-primary" id="pay-now">Checkout</button>

<script src="https://js.stripe.com/v3/"></script>

<script>
    const stripe = Stripe('<%= ENV["STRIPE_PK_TEST"] %>')

    function redirectToStripe() {
        stripe.redirectToCheckout({ sessionId: '<%= @session.id %>'})
    }

    document.querySelector("#pay-now").addEventListener("click", redirectToStripe)
</script>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">PopExchange</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <% if user_signed_in?%>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <% if user_signed_in?%>
        Welcome 
        <%= current_user.email %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/pops/_form.html.erb
<%= simple_form_for(@pop) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, required:true %>
    <%= f.input :description, required:true %>
    <%= f.input :price, required:true %>
    <%= f.input :category, collection: ["Avatar: The Last Airbender", "Borderlands", "Deadpool", "Fairy Tail", "My Hero Academia", "Skyrim"], required:true %>
    <%=f.file_field :picture, required:true %>
  </div>

  <div class="form-actions">
  <p>
  </p>
    <%= f.button :submit, class:"btn btn-primary btn-lg"%> 
  </div>
<% end %>

app/views/pops/edit.html.erb
<%= render 'form', pop: @pop %>

<%= link_to 'Back', pops_path, class:"btn btn-primary btn-lg" %>

app/views/pops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pops</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Category</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pops.each do |pop| %>
      <tr>
        <td><%= pop.name %></td>
        <td><%= pop.description %></td>
        <td><%= pop.price %></td>
        <td><%= pop.category %></td>
        <td><%= pop.user.email %></td>
        <td><%= link_to 'Show', pop, class:"btn btn-primary btn-lg" %></td>

        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Got one to Sell?', new_pop_path, class:"btn btn-primary btn-lg"%>

app/views/pops/new.html.erb
<h1>New Pop</h1>

<%= render 'form', pop: @pop %>
<p>
</p>

<%= link_to 'Back', pops_path, class:"btn btn-primary btn-lg"%>

app/views/pops/show.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
  <div class="row">
    <div class="col-md-4">
      <p>
        <dl>
          <dd>
            <strong>Name:</strong>
            <%= @pop.name %>
          </dd>
          <dd>
            <strong>Description:</strong>
            <%= @pop.description %>
          </dd>
          <dd>
            <strong>Price:</strong>
            <%= @pop.price %>
          </dd>
          <dd>
            <strong>Category:</strong>
            <%= @pop.category %>
          </dd>
          <dd>
          <%= link_to "Back",  pops_path, class:"btn btn-primary btn-lg" %>  |
          <% if current_user.id == @pop.user_id%>
            <%= link_to "Edit", edit_pop_path(@pop), class:"btn btn-primary btn-lg" %> |
            <%= link_to "Delete", delete_pop_path(@pop), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-primary btn-lg" %>
          <% else %> 
            <%=link_to "Buy", new_order_path(pop_id: @pop.id), class:"btn btn-primary btn-lg" %>
          <% end %>

          </dd>
        </dl>
      </p>
    </div>
    <div class="col-md-4">
    <% if  @pop.picture.attached? == true%>
      <%= image_tag @pop.picture, class:"popDisplayPic" %>
    <% else %>
    Please upload an image so poeple can see that you have the Pop!
    <% end %>
    
    </div> 
  </div>
</div>
<%#  %>